name: Neon Database Branching

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  neon_branching:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Neon Branch
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        run: |
          curl --request POST \
          --url "https://console.neon.tech/api/v2/projects/${{ secrets.NEON_PROJECT_ID }}/branches" \
          --header "Accept: application/json" \
          --header "Authorization: Bearer ${{ secrets.NEON_API_KEY }}" \
          --header "Content-Type: application/json" \
          --data "{
            \"branch\": {
              \"name\": \"pr-${{ github.event.pull_request.number }}\",
              \"parent_id\": \"main\"
            }
          }"

      - name: Delete Neon Branch
        if: github.event.action == 'closed'
        run: |
          curl --request DELETE \
          --url "https://console.neon.tech/api/v2/projects/${{ secrets.NEON_PROJECT_ID }}/branches/pr-${{ github.event.pull_request.number }}" \
          --header "Accept: application/json" \
          --header "Authorization: Bearer ${{ secrets.NEON_API_KEY }}"
