services:
  - type: web
    name: task-manager-api
    env: node
    rootDir: task-manager-backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://task-app-ps4f.vercel.app

databases:
  - name: task-manager-db
    databaseName: taskmanager
    plan: free
